<?php

// Connstante URL
define("URL", str_replace("index.php","",(isset($_SERVER['HTTPS']) ? "https" : "http").
"://$_SERVER[HTTP_HOST]$_SERVER[PHP_SELF]"));

// Fonction formatage date
function formatDate($date){
    $english_months = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
    $french_months = array('janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre');
    return str_replace($english_months, $french_months, str_replace("-", " ", date('j-F-Y', strtotime($date))));
}

function displaySpecialitiesBySpyInMissionForm($idSpy, $SpecialitiesArray){
    foreach($SpecialitiesArray as $table){
        if($table['id_spy'] === $idSpy){
            $string = $table['name'];
            echo " - " . $string;  
        }
    }
}

function giveArrayCountry(){
$countryArray = array(
    'AF' => 'Afghanistan',
    'ZA' => 'Afrique du Sud',
    'AL' => 'Albanie',
    'DZ' => 'Algérie',
    'DE' => 'Allemagne',
    'MK' => 'Ancienne République yougoslave de Macédoine',
    'AD' => 'Andorre',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctique',
    'AG' => 'Antigua-et-Barbuda',
    'AN' => 'Antilles néerlandaises',
    'SA' => 'Arabie saoudite',
    'AR' => 'Argentine',
    'AM' => 'Arménie',
    'AW' => 'Aruba',
    'AU' => 'Australie',
    'AT' => 'Autriche',
    'AZ' => 'Azerbaïdjan',
    'BS' => 'Bahamas',
    'BH' => 'Bahreïn',
    'BD' => 'Bangladesh',
    'BB' => 'Barbade',
    'BE' => 'Belgique',
    'BZ' => 'Belize',
    'BJ' => 'Bénin',
    'BM' => 'Bermudes',
    'BT' => 'Bhoutan',
    'BY' => 'Biélorussie',
    'BO' => 'Bolivie',
    'BA' => 'Bosnie-et-Herzégovine',
    'BW' => 'Botswana',
    'BR' => 'Brésil',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgarie',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodge',
    'CM' => 'Cameroun',
    'CA' => 'Canada',
    'CV' => 'Cap-Vert',
    'CL' => 'Chili',
    'CN' => 'Chine',
    'CY' => 'Chypre',
    'CO' => 'Colombie',
    'KM' => 'Comores',
    'CG' => 'Congo',
    'CR' => 'Costa Rica',
    'CI' => 'Côte d\'Ivoire',
    'HR' => 'Croatie',
    'CU' => 'Cuba',
    'DK' => 'Danemark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominique',
    'EG' => 'Égypte',
    'SV' => 'El Salvador',
    'AE' => 'Émirats arabes unis',
    'EC' => 'Équateur',
    'ER' => 'Érythrée',
    'ES' => 'Espagne',
     'EE' => 'Estonie',
    'FM' => 'États fédérés de Micronésie',
    'US' => 'États-Unis',
    'ET' => 'Éthiopie',
    'FJ' => 'Fidji',
    'FI' => 'Finlande',
    'FR' => 'France',
    'GA' => 'Gabon',
    'GM' => 'Gambie',
    'GE' => 'Géorgie',
    'GS' => 'Géorgie du Sud-et-les Îles Sandwich du Sud',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Grèce',
    'GD' => 'Grenade',
    'GL' => 'Groenland',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GN' => 'Guinée',
    'GQ' => 'Guinée équatoriale',
    'GW' => 'Guinée-Bissau',
    'GY' => 'Guyane',
    'GF' => 'Guyane française',
    'HT' => 'Haïti',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hongrie',
    'BV' => 'Ile Bouvet',
    'CX' => 'Ile Christmas',
    'NF' => 'Île Norfolk',
    'PN' => 'Île Pitcairn',
    'AX' => 'Iles Aland',
    'KY' => 'Iles Cayman',
    'CC' => 'Iles Cocos (Keeling)',
    'CK' => 'Iles Cook',
    'FO' => 'Îles Féroé',
    'HM' => 'Îles Heard-et-MacDonald',
    'FK' => 'Îles Malouines',
    'MP' => 'Îles Mariannes du Nord',
    'MH' => 'Îles Marshall',
    'UM' => 'Îles mineures éloignées des États-Unis',
    'SB' => 'Îles Salomon',
    'TC' => 'Îles Turques-et-Caïques',
    'VG' => 'Îles Vierges britanniques',
    'VI' => 'Îles Vierges des États-Unis',
    'IN' => 'Inde',
    'ID' => 'Indonésie',
    'IQ' => 'Iraq',
    'IE' => 'Irlande',
    'IS' => 'Islande',
    'IL' => 'Israël',
    'IT' => 'Italie',
    'LY' => 'Jamahiriya arabe libyenne',
    'JM' => 'Jamaïque',
    'JP' => 'Japon',
    'JO' => 'Jordanie',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KG' => 'Kirghizistan',
    'KI' => 'Kiribati',
    'KW' => 'Koweït',
    'LS' => 'Lesotho',
    'LV' => 'Lettonie',
    'LB' => 'Liban',
    'LR' => 'Libéria',
    'LI' => 'Liechtenstein',
    'LT' => 'Lituanie',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MG' => 'Madagascar',
    'MY' => 'Malaisie',
    'MW' => 'Malawi',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malte',
    'MA' => 'Maroc',
    'MQ' => 'Martinique',
    'MU' => 'Maurice',
    'MR' => 'Mauritanie',
    'YT' => 'Mayotte',
    'MX' => 'Mexique',
    'MC' => 'Monaco',
    'MN' => 'Mongolie',
    'MS' => 'Montserrat',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibie',
    'NR' => 'Nauru',
    'NP' => 'Népal',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigéria',
    'NU' => 'Niué',
    'NO' => 'Norvège',
    'NC' => 'Nouvelle-Calédonie',
    'NZ' => 'Nouvelle-Zélande',
    'OM' => 'Oman',
    'UG' => 'Ouganda',
    'UZ' => 'Ouzbékistan',
    'PK' => 'Pakistan',
    'PW' => 'Palaos',
    'PA' => 'Panama',
    'PG' => 'Papouasie-Nouvelle-Guinée',
    'PY' => 'Paraguay',
    'NL' => 'Pays-Bas',
    'PE' => 'Pérou',
    'PH' => 'Philippines',
    'PL' => 'Pologne',
    'PF' => 'Polynésie française',
    'PR' => 'Porto Rico',
    'PT' => 'Portugal',
    'TW' => 'Province chinoise de Taiwan',
    'QA' => 'Qatar',
    'SY' => 'République arabe syrienne',
    'CF' => 'République centrafricaine',
    'KR' => 'République de Corée',
    'MD' => 'République de Moldavie',
    'CD' => 'République démocratique du Congo',
    'DO' => 'République dominicaine',
    'IR' => 'République islamique d\'Iran',
    'KP' => 'République populaire démocratique de Corée',
    'LA' => 'République Populaire du Laos',
    'CZ' => 'République tchèque',
    'TZ' => 'République-Unie de Tanzanie',
    'RE' => 'Réunion',
    'RO' => 'Roumanie',
    'GB' => 'Royaume-Uni',
    'RU' => 'Russie',
    'RW' => 'Rwanda',
    'EH' => 'Sahara occidental',
    'KN' => 'Saint-Christophe-et-Niévès',
    'SM' => 'Saint-Marin',
    'PM' => 'Saint-Pierre-et-Miquelon',
    'VA' => 'Saint-Siège (Cité du Vatican)',
    'VC' => 'Saint-Vincent-et-les Grenadines',
    'SH' => 'Sainte-Hélène',
    'LC' => 'Sainte-Lucie',
    'WS' => 'Samoa',
    'AS' => 'Samoa américaines',
    'ST' => 'Sao Tomé-et-Principe',
    'SN' => 'Sénégal',
    'CS' => 'Serbie-et-Monténégro',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapour',
    'SK' => 'Slovaquie',
    'SI' => 'Slovénie',
    'SO' => 'Somalie',
    'SD' => 'Soudan',
    'LK' => 'Sri Lanka',
    'SE' => 'Suède',
    'CH' => 'Suisse',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard et Jan Mayen',
    'SZ' => 'Swaziland',
    'TJ' => 'Tadjikistan',
    'TD' => 'Tchad',
    'IO' => 'Territoire britannique de l\'océan Indien',
    'TF' => 'Territoire Francais du Sud',
    'PS' => 'Territoires palestiniens occupés',
    'TH' => 'Thaïlande',
    'TL' => 'Timor oriental',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinité-et-Tobago',
    'TN' => 'Tunisie',
    'TM' => 'Turkménistan',
    'TR' => 'Turquie',
    'TV' => 'Tuvalu',
    'UA' => 'Ukraine',
    'UY' => 'Uruguay',
    'VU' => 'Vanuatu',
    'VE' => 'Vénézuéla',
    'VN' => 'Vietnam',
    'WF' => 'Wallis-et-Futuna',
    'YE' => 'Yémen',
    'ZM' => 'Zambie',
    'ZW' => 'Zimbabwe'
);

    return $countryArray;
}

// function code_country en nom country
function getCountryByCodeCountry($codeCountry, $array){
    $country = $array;
    foreach($country as $clef => $valeur){
        if($clef === $codeCountry){
            return $valeur;
        }
    }
}
